version: "3.8"

services:
  postgres:
    image: postgres:latest
    container_name: giaithuat-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: giaithuat
      # Create n8n database on startup
      POSTGRES_MULTIPLE_DATABASES: "n8n"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  n8n:
    image: n8nio/n8n:latest
    container_name: giaithuat-n8n
    restart: always
    ports:
      - "5678:5678"
    environment:
      - N8N_PORT=5678
      - DB_TYPE=postgresdb
      - DB_POSTGRESDB_HOST=postgres
      - DB_POSTGRESDB_PORT=5432
      - DB_POSTGRESDB_DATABASE=n8n
      - DB_POSTGRESDB_USER=postgres
      - DB_POSTGRESDB_PASSWORD=postgres
      - N8N_ENCRYPTION_KEY=a-very-secure-encryption-key-change-me
      - N8N_RUNNERS_ENABLED=true
      - N8N_BLOCK_FILE_ACCESS_TO_N8N_FILES=false
    volumes:
      - ./n8n_data:/home/node/.n8n
    depends_on:
      - postgres

volumes:
  postgres_data:
    name: giaithuat-postgres-data
