version: "3.8"

services:
  postgres:
    image: postgres:latest
    container_name: giaithuat-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: giaithuat
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
    name: giaithuat-postgres-data
