services:
  postgres:
    image: postgres:17-alpine
    container_name: giaithuat-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: giaithuat
    volumes:
      - ./volumes/postgres_data:/var/lib/postgresql/data
  n8n:
    image: n8nio/n8n:latest
    container_name: giaithuat-n8n
    ports:
      - "5678:5678"
    environment:
      - N8N_PORT=5678
      - DB_TYPE=postgresdb
      - DB_POSTGRESDB_HOST=postgres
      - DB_POSTGRESDB_PORT=5432
      - DB_POSTGRESDB_DATABASE=n8n
      - DB_POSTGRESDB_USER=postgres
      - DB_POSTGRESDB_PASSWORD=postgres
      - N8N_ENCRYPTION_KEY=a-very-secure-encryption-key-change-me
      - N8N_RUNNERS_ENABLED=true
      - N8N_BLOCK_FILE_ACCESS_TO_N8N_FILES=false
    volumes:
      - ./volumes/n8n_data:/home/node/.n8n
    depends_on:
      - postgres
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: giaithuat-pgadmin
    ports:
      - "5050:80"
    environment:
      - PGADMIN_DEFAULT_EMAIL=root@admin.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    volumes:
      - ./volumes/pgadmin_data:/pgadmin4/servers.json
