"""create user_activity

Revision ID: 021de34b4f54
Revises: 48a509127b76
Create Date: 2025-08-25 04:40:11.213221

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "021de34b4f54"
down_revision: Union[str, None] = "48a509127b76"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user_activities",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column(
            "activity_type",
            sa.Enum(
                "EXERCISE",
                "COURSE",
                "DISCUSSION",
                "LESSON",
                "TEST",
                "BADGE",
                name="activitytype",
            ),
            nullable=False,
        ),
        sa.Column("activity_name", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("score", sa.Integer(), nullable=True),
        sa.Column("progress", sa.String(length=50), nullable=True),
        sa.Column("related_id", sa.Integer(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_user_activities_activity_type"),
        "user_activities",
        ["activity_type"],
        unique=False,
    )
    op.create_index(
        op.f("ix_user_activities_created_at"),
        "user_activities",
        ["created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_user_activities_id"), "user_activities", ["id"], unique=False
    )
    op.create_index(
        op.f("ix_user_activities_updated_at"),
        "user_activities",
        ["updated_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_user_activities_user_id"), "user_activities", ["user_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_user_activities_user_id"), table_name="user_activities")
    op.drop_index(op.f("ix_user_activities_updated_at"), table_name="user_activities")
    op.drop_index(op.f("ix_user_activities_id"), table_name="user_activities")
    op.drop_index(op.f("ix_user_activities_created_at"), table_name="user_activities")
    op.drop_index(
        op.f("ix_user_activities_activity_type"), table_name="user_activities"
    )
    op.drop_table("user_activities")

    op.execute("DROP TYPE activitytype")
    # ### end Alembic commands ###
