"""update_user_assessments_focus_on_weaknesses

Revision ID: 0c37c6ef4468
Revises: 1394bc6843ab
Create Date: 2025-08-03 16:15:56.825417

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0c37c6ef4468'
down_revision: Union[str, None] = '1394bc6843ab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_user_assessments_updated_at'), 'user_assessments', ['updated_at'], unique=False)
    op.drop_column('user_assessments', 'raw_analysis')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_assessments', sa.Column('raw_analysis', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True, comment='Dữ liệu phân tích thô từ agent'))
    op.drop_index(op.f('ix_user_assessments_updated_at'), table_name='user_assessments')
    # ### end Alembic commands ###
