"""Make start_time nullable in test_sessions

Revision ID: 0dff4ed1058e
Revises: 8b2e1f8bb9b1
Create Date: 2025-06-28 01:51:02.396082

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0dff4ed1058e'
down_revision: Union[str, None] = '8b2e1f8bb9b1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
