"""add_course_draft_and_review_chat_tables

Revision ID: 11ef3ca88549
Revises: 1e247207d508
Create Date: 2025-08-03 09:52:52.044382

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '11ef3ca88549'
down_revision: Union[str, None] = '1e247207d508'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('course_drafts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('agent_content', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_course_drafts_id'), 'course_drafts', ['id'], unique=False)
    op.create_table('course_review_chats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('is_agent', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_course_review_chats_id'), 'course_review_chats', ['id'], unique=False)
    op.create_index(op.f('ix_course_review_chats_updated_at'), 'course_review_chats', ['updated_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_course_review_chats_updated_at'), table_name='course_review_chats')
    op.drop_index(op.f('ix_course_review_chats_id'), table_name='course_review_chats')
    op.drop_table('course_review_chats')
    op.drop_index(op.f('ix_course_drafts_id'), table_name='course_drafts')
    op.drop_table('course_drafts')
    # ### end Alembic commands ###
