"""update_user_assessments_focus_on_weaknesses

Revision ID: 1394bc6843ab
Revises: 727b15633bb0
Create Date: 2025-08-03 16:13:53.711906

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1394bc6843ab'
down_revision: Union[str, None] = '727b15633bb0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_assessments', sa.Column('skill_name', sa.String(), nullable=False, comment='Tên skill được đánh giá'))
    op.add_column('user_assessments', sa.Column('weakness_analysis', sa.Text(), nullable=True, comment='Phân tích chi tiết về các điểm yếu'))
    op.add_column('user_assessments', sa.Column('improvement_suggestions', sa.JSON(), nullable=True, comment='Gợi ý cụ thể để cải thiện điểm yếu'))
    op.add_column('user_assessments', sa.Column('current_level', sa.String(), nullable=True, comment='Mức độ hiện tại của user trong skill'))
    op.add_column('user_assessments', sa.Column('weakness_severity', sa.String(), nullable=True, comment='Mức độ nghiêm trọng của điểm yếu: Low/Medium/High'))
    op.alter_column('user_assessments', 'weaknesses',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment='Các điểm yếu cụ thể trong skill',
               existing_comment='Điểm yếu của người dùng',
               existing_nullable=True)
    op.drop_column('user_assessments', 'proficiency_level')
    op.drop_column('user_assessments', 'learning_path')
    op.drop_column('user_assessments', 'analysis_summary')
    op.drop_column('user_assessments', 'skill_levels')
    op.drop_column('user_assessments', 'recommendations')
    op.drop_column('user_assessments', 'overall_score')
    op.drop_column('user_assessments', 'strengths')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_assessments', sa.Column('strengths', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True, comment='Điểm mạnh của người dùng'))
    op.add_column('user_assessments', sa.Column('overall_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True, comment='Điểm số tổng quan'))
    op.add_column('user_assessments', sa.Column('recommendations', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True, comment='Khuyến nghị cải thiện'))
    op.add_column('user_assessments', sa.Column('skill_levels', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True, comment='Mức độ kỹ năng theo từng chủ đề'))
    op.add_column('user_assessments', sa.Column('analysis_summary', sa.TEXT(), autoincrement=False, nullable=True, comment='Tóm tắt phân tích'))
    op.add_column('user_assessments', sa.Column('learning_path', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True, comment='Lộ trình học tập được đề xuất'))
    op.add_column('user_assessments', sa.Column('proficiency_level', sa.VARCHAR(), autoincrement=False, nullable=True, comment='Mức độ thành thạo: beginner, intermediate, advanced'))
    op.alter_column('user_assessments', 'weaknesses',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment='Điểm yếu của người dùng',
               existing_comment='Các điểm yếu cụ thể trong skill',
               existing_nullable=True)
    op.drop_column('user_assessments', 'weakness_severity')
    op.drop_column('user_assessments', 'current_level')
    op.drop_column('user_assessments', 'improvement_suggestions')
    op.drop_column('user_assessments', 'weakness_analysis')
    op.drop_column('user_assessments', 'skill_name')
    # ### end Alembic commands ###
