"""add column current lesson to user_topics table

Revision ID: 1d8c8dffe7ab
Revises: e0dc8fd6b0f8
Create Date: 2025-07-11 10:02:40.527504

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1d8c8dffe7ab'
down_revision: Union[str, None] = 'e0dc8fd6b0f8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_topics', sa.Column('current_lesson_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'user_topics', 'lessons', ['current_lesson_id'], ['id'])
    op.drop_column('user_topics', 'total_lessons')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_topics', sa.Column('total_lessons', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'user_topics', type_='foreignkey')
    op.drop_column('user_topics', 'current_lesson_id')
    # ### end Alembic commands ###
