"""add_skill_model

Revision ID: 1e247207d508
Revises: e9693a8c55ad
Create Date: 2025-08-03 08:48:08.783077

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1e247207d508'
down_revision: Union[str, None] = 'e9693a8c55ad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('skills',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('topic_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_skills_created_at'), 'skills', ['created_at'], unique=False)
    op.create_index(op.f('ix_skills_id'), 'skills', ['id'], unique=False)
    op.create_index(op.f('ix_skills_topic_id'), 'skills', ['topic_id'], unique=False)
    op.create_index(op.f('ix_skills_updated_at'), 'skills', ['updated_at'], unique=False)
    op.drop_index(op.f('ix_course_drafts_id'), table_name='course_drafts')
    op.drop_table('course_drafts')
    op.drop_index(op.f('ix_course_review_chats_id'), table_name='course_review_chats')
    op.drop_index(op.f('ix_course_review_chats_updated_at'), table_name='course_review_chats')
    op.drop_table('course_review_chats')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('course_review_chats',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('course_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('message', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('is_agent', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], name=op.f('course_review_chats_course_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('course_review_chats_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('course_review_chats_pkey'))
    )
    op.create_index(op.f('ix_course_review_chats_updated_at'), 'course_review_chats', ['updated_at'], unique=False)
    op.create_index(op.f('ix_course_review_chats_id'), 'course_review_chats', ['id'], unique=False)
    op.create_table('course_drafts',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('course_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('agent_content', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], name=op.f('course_drafts_course_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('course_drafts_pkey'))
    )
    op.create_index(op.f('ix_course_drafts_id'), 'course_drafts', ['id'], unique=False)
    op.drop_index(op.f('ix_skills_updated_at'), table_name='skills')
    op.drop_index(op.f('ix_skills_topic_id'), table_name='skills')
    op.drop_index(op.f('ix_skills_id'), table_name='skills')
    op.drop_index(op.f('ix_skills_created_at'), table_name='skills')
    op.drop_table('skills')
    # ### end Alembic commands ###
