"""remove column lesson table

Revision ID: 23cbd4e439a3
Revises: 5dab222ffb2e
Create Date: 2025-08-20 13:13:25.720438

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '23cbd4e439a3'
down_revision: Union[str, None] = '5dab222ffb2e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('lessons', 'prev_lesson_id')
    op.drop_column('lessons', 'next_lesson_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lessons', sa.Column('next_lesson_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('lessons', sa.Column('prev_lesson_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
