"""add status column to user course tabel

Revision ID: 2dd4aa3c9492
Revises: 23cbd4e439a3
Create Date: 2025-08-22 05:47:10.454545

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2dd4aa3c9492'
down_revision: Union[str, None] = '23cbd4e439a3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_courses', sa.Column('status', sa.String(), nullable=True))
    op.create_index(op.f('ix_user_courses_status'), 'user_courses', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_courses_status'), table_name='user_courses')
    op.drop_column('user_courses', 'status')
    # ### end Alembic commands ###
