"""remove course chat table

Revision ID: 2f9839812071
Revises: 0c37c6ef4468
Create Date: 2025-08-04 06:13:45.447568

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2f9839812071'
down_revision: Union[str, None] = '0c37c6ef4468'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_course_review_chats_id'), table_name='course_review_chats')
    op.drop_index(op.f('ix_course_review_chats_updated_at'), table_name='course_review_chats')
    op.drop_table('course_review_chats')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('course_review_chats',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('course_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('message', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('is_agent', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], name=op.f('course_review_chats_course_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('course_review_chats_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('course_review_chats_pkey'))
    )
    op.create_index(op.f('ix_course_review_chats_updated_at'), 'course_review_chats', ['updated_at'], unique=False)
    op.create_index(op.f('ix_course_review_chats_id'), 'course_review_chats', ['id'], unique=False)
    # ### end Alembic commands ###
