"""feat: add course_id to topic table and add relationship

Revision ID: 30c5b3b4b604
Revises: cbf3b82a6360
Create Date: 2025-06-26 17:06:34.544148

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '30c5b3b4b604'
down_revision: Union[str, None] = 'cbf3b82a6360'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('topics', sa.Column('course_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'topics', 'courses', ['course_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'topics', type_='foreignkey')
    op.drop_column('topics', 'course_id')
    # ### end Alembic commands ###
