"""a

Revision ID: 3c0cb9d4e50c
Revises: 9bad74a74ea9
Create Date: 2025-08-25 03:41:30.741493

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3c0cb9d4e50c'
down_revision: Union[str, None] = '9bad74a74ea9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_activities', 'activity_type',
               existing_type=postgresql.ENUM('exercise', 'course', 'discussion', 'lesson', 'test', 'badge', name='activitytype'),
               type_=sa.Enum('EXERCISE', 'COURSE', 'DISCUSSION', 'LESSON', 'TEST', 'BADGE', name='activitytype', native_enum=False),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_activities', 'activity_type',
               existing_type=sa.Enum('EXERCISE', 'COURSE', 'DISCUSSION', 'LESSON', 'TEST', 'BADGE', name='activitytype', native_enum=False),
               type_=postgresql.ENUM('exercise', 'course', 'discussion', 'lesson', 'test', 'badge', name='activitytype'),
               existing_nullable=False)
    # ### end Alembic commands ###
