"""initial

Revision ID: 3f4d92aaa3b3
Revises:
Create Date: 2025-07-01 16:19:27.970284

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "3f4d92aaa3b3"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "badges",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("icon", sa.String(length=50), nullable=True),
        sa.Column("image_url", sa.String(length=500), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("category", sa.String(length=50), nullable=True),
        sa.Column("criteria", sa.Text(), nullable=True),
        sa.Column("points", sa.Integer(), nullable=True),
        sa.Column("rarity", sa.String(length=50), nullable=True),
        sa.Column("is_hidden", sa.Boolean(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_badges_created_at"), "badges", ["created_at"], unique=False
    )
    op.create_index(op.f("ix_badges_id"), "badges", ["id"], unique=False)
    op.create_index(
        op.f("ix_badges_updated_at"), "badges", ["updated_at"], unique=False
    )
    op.create_table(
        "courses",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("thumbnail_url", sa.String(length=500), nullable=True),
        sa.Column("level", sa.String(length=50), nullable=False),
        sa.Column("duration", sa.Integer(), nullable=False),
        sa.Column("price", sa.Float(), nullable=False),
        sa.Column("is_published", sa.Boolean(), nullable=False),
        sa.Column("test_generation_status", sa.String(length=20), nullable=False),
        sa.Column("tags", sa.String(length=255), nullable=False),
        sa.Column("requirements", sa.Text(), nullable=True),
        sa.Column("what_you_will_learn", sa.Text(), nullable=True),
        sa.Column("learning_path", sa.Text(), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_courses_created_at"), "courses", ["created_at"], unique=False
    )
    op.create_index(op.f("ix_courses_id"), "courses", ["id"], unique=False)
    op.create_index(
        op.f("ix_courses_updated_at"), "courses", ["updated_at"], unique=False
    )
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("email", sa.String(), nullable=False),
        sa.Column("username", sa.String(), nullable=False),
        sa.Column("hashed_password", sa.String(), nullable=False),
        sa.Column("full_name", sa.String(), nullable=True),
        sa.Column("first_name", sa.String(), nullable=True),
        sa.Column("last_name", sa.String(), nullable=True),
        sa.Column("avatar", sa.String(), nullable=True),
        sa.Column("bio", sa.String(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("is_admin", sa.Boolean(), server_default="false", nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_users_created_at"), "users", ["created_at"], unique=False)
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)
    op.create_index(op.f("ix_users_id"), "users", ["id"], unique=False)
    op.create_index(op.f("ix_users_updated_at"), "users", ["updated_at"], unique=False)
    op.create_index(op.f("ix_users_username"), "users", ["username"], unique=True)
    op.create_table(
        "topics",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("course_id", sa.Integer(), nullable=True),
        sa.Column("external_id", sa.String(), nullable=True),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("description", sa.String(), nullable=False),
        sa.Column("prerequisites", sa.ARRAY(sa.String()), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["course_id"],
            ["courses.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_topics_created_at"), "topics", ["created_at"], unique=False
    )
    op.create_index(
        op.f("ix_topics_external_id"), "topics", ["external_id"], unique=True
    )
    op.create_index(op.f("ix_topics_id"), "topics", ["id"], unique=False)
    op.create_index(op.f("ix_topics_name"), "topics", ["name"], unique=False)
    op.create_index(
        op.f("ix_topics_updated_at"), "topics", ["updated_at"], unique=False
    )
    op.create_table(
        "user_badges",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("badge_id", sa.Integer(), nullable=False),
        sa.Column(
            "earned_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("is_featured", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["badge_id"],
            ["badges.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_user_badges_created_at"), "user_badges", ["created_at"], unique=False
    )
    op.create_index(op.f("ix_user_badges_id"), "user_badges", ["id"], unique=False)
    op.create_index(
        op.f("ix_user_badges_updated_at"), "user_badges", ["updated_at"], unique=False
    )
    op.create_table(
        "user_courses",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("course_id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.ForeignKeyConstraint(["course_id"], ["courses.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_user_courses_created_at"), "user_courses", ["created_at"], unique=False
    )
    op.create_index(op.f("ix_user_courses_id"), "user_courses", ["id"], unique=False)
    op.create_index(
        op.f("ix_user_courses_updated_at"), "user_courses", ["updated_at"], unique=False
    )
    op.create_table(
        "lessons",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("external_id", sa.String(), nullable=False),
        sa.Column("title", sa.String(), nullable=False),
        sa.Column("description", sa.String(), nullable=False),
        sa.Column("topic_id", sa.Integer(), nullable=False),
        sa.Column("order", sa.Integer(), nullable=False),
        sa.Column("next_lesson_id", sa.String(), nullable=True),
        sa.Column("prev_lesson_id", sa.String(), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["topic_id"],
            ["topics.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_lessons_created_at"), "lessons", ["created_at"], unique=False
    )
    op.create_index(
        op.f("ix_lessons_description"), "lessons", ["description"], unique=False
    )
    op.create_index(
        op.f("ix_lessons_external_id"), "lessons", ["external_id"], unique=True
    )
    op.create_index(op.f("ix_lessons_id"), "lessons", ["id"], unique=False)
    op.create_index(op.f("ix_lessons_title"), "lessons", ["title"], unique=False)
    op.create_index(
        op.f("ix_lessons_updated_at"), "lessons", ["updated_at"], unique=False
    )
    op.create_table(
        "tests",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("topic_id", sa.Integer(), nullable=True),
        sa.Column("course_id", sa.Integer(), nullable=True),
        sa.Column("duration_minutes", sa.Integer(), nullable=True),
        sa.Column("questions", sa.JSON(), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["course_id"],
            ["courses.id"],
        ),
        sa.ForeignKeyConstraint(
            ["topic_id"],
            ["topics.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_tests_created_at"), "tests", ["created_at"], unique=False)
    op.create_index(op.f("ix_tests_updated_at"), "tests", ["updated_at"], unique=False)
    op.create_table(
        "user_topics",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("topic_id", sa.Integer(), nullable=False),
        sa.Column("progress", sa.Integer(), nullable=False),
        sa.Column("completed_lessons", sa.Integer(), nullable=False),
        sa.Column("total_lessons", sa.Integer(), nullable=False),
        sa.Column("is_completed", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["topic_id"],
            ["topics.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_user_topics_created_at"), "user_topics", ["created_at"], unique=False
    )
    op.create_index(op.f("ix_user_topics_id"), "user_topics", ["id"], unique=False)
    op.create_index(
        op.f("ix_user_topics_updated_at"), "user_topics", ["updated_at"], unique=False
    )
    op.create_table(
        "exercises",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("description", sa.String(), nullable=False),
        sa.Column("difficulty", sa.String(), nullable=False),
        sa.Column("constraint", sa.String(), nullable=True),
        sa.Column("lesson_id", sa.Integer(), nullable=False),
        sa.Column("suggest", sa.String(), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["lesson_id"],
            ["lessons.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_exercises_created_at"), "exercises", ["created_at"], unique=False
    )
    op.create_index(
        op.f("ix_exercises_updated_at"), "exercises", ["updated_at"], unique=False
    )
    op.create_table(
        "lesson_sections",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("lesson_id", sa.Integer(), nullable=False),
        sa.Column("type", sa.String(), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("order", sa.Integer(), nullable=False),
        sa.Column("options", sa.JSON(), nullable=True),
        sa.Column("answer", sa.Integer(), nullable=True),
        sa.Column("explanation", sa.Text(), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["lesson_id"],
            ["lessons.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_lesson_sections_created_at"),
        "lesson_sections",
        ["created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_lesson_sections_id"), "lesson_sections", ["id"], unique=False
    )
    op.create_index(
        op.f("ix_lesson_sections_type"), "lesson_sections", ["type"], unique=False
    )
    op.create_index(
        op.f("ix_lesson_sections_updated_at"),
        "lesson_sections",
        ["updated_at"],
        unique=False,
    )
    op.create_table(
        "test_sessions",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("test_id", sa.Integer(), nullable=False),
        sa.Column("start_time", sa.DateTime(), nullable=True),
        sa.Column("end_time", sa.DateTime(), nullable=True),
        sa.Column("last_activity", sa.DateTime(), nullable=False),
        sa.Column("time_remaining_seconds", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("is_submitted", sa.Boolean(), nullable=False),
        sa.Column("current_question_index", sa.Integer(), nullable=False),
        sa.Column("answers", sa.JSON(), nullable=False),
        sa.Column("score", sa.Integer(), nullable=True),
        sa.Column("correct_answers", sa.Integer(), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["test_id"],
            ["tests.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_test_sessions_created_at"),
        "test_sessions",
        ["created_at"],
        unique=False,
    )
    op.create_index(op.f("ix_test_sessions_id"), "test_sessions", ["id"], unique=False)
    op.create_index(
        op.f("ix_test_sessions_last_activity"),
        "test_sessions",
        ["last_activity"],
        unique=False,
    )
    op.create_index(
        op.f("ix_test_sessions_start_time"),
        "test_sessions",
        ["start_time"],
        unique=False,
    )
    op.create_index(
        op.f("ix_test_sessions_test_id"), "test_sessions", ["test_id"], unique=False
    )
    op.create_index(
        op.f("ix_test_sessions_updated_at"),
        "test_sessions",
        ["updated_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_test_sessions_user_id"), "test_sessions", ["user_id"], unique=False
    )
    op.create_table(
        "user_lessons",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("lesson_id", sa.Integer(), nullable=False),
        sa.Column("is_completed", sa.Boolean(), nullable=False),
        sa.Column("progress", sa.Integer(), nullable=False),
        sa.Column("last_section_index", sa.Integer(), nullable=False),
        sa.Column("completed_at", sa.DateTime(), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["lesson_id"],
            ["lessons.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_user_lessons_created_at"), "user_lessons", ["created_at"], unique=False
    )
    op.create_index(op.f("ix_user_lessons_id"), "user_lessons", ["id"], unique=False)
    op.create_index(
        op.f("ix_user_lessons_updated_at"), "user_lessons", ["updated_at"], unique=False
    )
    op.create_table(
        "user_states",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column(
            "last_active",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("current_course_id", sa.Integer(), nullable=True),
        sa.Column("current_lesson_id", sa.Integer(), nullable=True),
        sa.Column("streak_last_date", sa.DateTime(timezone=True), nullable=True),
        sa.Column("streak_count", sa.Integer(), nullable=False),
        sa.Column("total_points", sa.Integer(), nullable=False),
        sa.Column("level", sa.Integer(), nullable=False),
        sa.Column("xp_to_next_level", sa.Integer(), nullable=False),
        sa.Column("daily_goal", sa.Integer(), nullable=False),
        sa.Column("daily_progress", sa.Integer(), nullable=False),
        sa.Column("completed_exercises", sa.Integer(), nullable=False),
        sa.Column("completed_courses", sa.Integer(), nullable=False),
        sa.Column("problems_solved", sa.Integer(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["current_course_id"],
            ["courses.id"],
        ),
        sa.ForeignKeyConstraint(
            ["current_lesson_id"],
            ["lessons.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id"),
    )
    op.create_index(
        op.f("ix_user_states_created_at"), "user_states", ["created_at"], unique=False
    )
    op.create_index(op.f("ix_user_states_id"), "user_states", ["id"], unique=False)
    op.create_index(
        op.f("ix_user_states_updated_at"), "user_states", ["updated_at"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_user_states_updated_at"), table_name="user_states")
    op.drop_index(op.f("ix_user_states_id"), table_name="user_states")
    op.drop_index(op.f("ix_user_states_created_at"), table_name="user_states")
    op.drop_table("user_states")
    op.drop_index(op.f("ix_user_lessons_updated_at"), table_name="user_lessons")
    op.drop_index(op.f("ix_user_lessons_id"), table_name="user_lessons")
    op.drop_index(op.f("ix_user_lessons_created_at"), table_name="user_lessons")
    op.drop_table("user_lessons")
    op.drop_index(op.f("ix_test_sessions_user_id"), table_name="test_sessions")
    op.drop_index(op.f("ix_test_sessions_updated_at"), table_name="test_sessions")
    op.drop_index(op.f("ix_test_sessions_test_id"), table_name="test_sessions")
    op.drop_index(op.f("ix_test_sessions_start_time"), table_name="test_sessions")
    op.drop_index(op.f("ix_test_sessions_last_activity"), table_name="test_sessions")
    op.drop_index(op.f("ix_test_sessions_id"), table_name="test_sessions")
    op.drop_index(op.f("ix_test_sessions_created_at"), table_name="test_sessions")
    op.drop_table("test_sessions")
    op.drop_index(op.f("ix_lesson_sections_updated_at"), table_name="lesson_sections")
    op.drop_index(op.f("ix_lesson_sections_type"), table_name="lesson_sections")
    op.drop_index(op.f("ix_lesson_sections_id"), table_name="lesson_sections")
    op.drop_index(op.f("ix_lesson_sections_created_at"), table_name="lesson_sections")
    op.drop_table("lesson_sections")
    op.drop_index(op.f("ix_exercises_updated_at"), table_name="exercises")
    op.drop_index(op.f("ix_exercises_created_at"), table_name="exercises")
    op.drop_table("exercises")
    op.drop_index(op.f("ix_user_topics_updated_at"), table_name="user_topics")
    op.drop_index(op.f("ix_user_topics_id"), table_name="user_topics")
    op.drop_index(op.f("ix_user_topics_created_at"), table_name="user_topics")
    op.drop_table("user_topics")
    op.drop_index(op.f("ix_tests_updated_at"), table_name="tests")
    op.drop_index(op.f("ix_tests_created_at"), table_name="tests")
    op.drop_table("tests")
    op.drop_index(op.f("ix_lessons_updated_at"), table_name="lessons")
    op.drop_index(op.f("ix_lessons_title"), table_name="lessons")
    op.drop_index(op.f("ix_lessons_id"), table_name="lessons")
    op.drop_index(op.f("ix_lessons_external_id"), table_name="lessons")
    op.drop_index(op.f("ix_lessons_description"), table_name="lessons")
    op.drop_index(op.f("ix_lessons_created_at"), table_name="lessons")
    op.drop_table("lessons")
    op.drop_index(op.f("ix_user_courses_updated_at"), table_name="user_courses")
    op.drop_index(op.f("ix_user_courses_id"), table_name="user_courses")
    op.drop_index(op.f("ix_user_courses_created_at"), table_name="user_courses")
    op.drop_table("user_courses")
    op.drop_index(op.f("ix_user_badges_updated_at"), table_name="user_badges")
    op.drop_index(op.f("ix_user_badges_id"), table_name="user_badges")
    op.drop_index(op.f("ix_user_badges_created_at"), table_name="user_badges")
    op.drop_table("user_badges")
    op.drop_index(op.f("ix_topics_updated_at"), table_name="topics")
    op.drop_index(op.f("ix_topics_name"), table_name="topics")
    op.drop_index(op.f("ix_topics_id"), table_name="topics")
    op.drop_index(op.f("ix_topics_external_id"), table_name="topics")
    op.drop_index(op.f("ix_topics_created_at"), table_name="topics")
    op.drop_table("topics")
    op.drop_index(op.f("ix_users_username"), table_name="users")
    op.drop_index(op.f("ix_users_updated_at"), table_name="users")
    op.drop_index(op.f("ix_users_id"), table_name="users")
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.drop_index(op.f("ix_users_created_at"), table_name="users")
    op.drop_table("users")
    op.drop_index(op.f("ix_courses_updated_at"), table_name="courses")
    op.drop_index(op.f("ix_courses_id"), table_name="courses")
    op.drop_index(op.f("ix_courses_created_at"), table_name="courses")
    op.drop_table("courses")
    op.drop_index(op.f("ix_badges_updated_at"), table_name="badges")
    op.drop_index(op.f("ix_badges_id"), table_name="badges")
    op.drop_index(op.f("ix_badges_created_at"), table_name="badges")
    op.drop_table("badges")
    # ### end Alembic commands ###
