"""add course_id to test table and make topic_id nullable

Revision ID: 3f8b2e84b5eb
Revises: 6863b934155f
Create Date: 2025-06-27 02:15:49.396950

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3f8b2e84b5eb'
down_revision: Union[str, None] = '6863b934155f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_badges_created_at'), 'badges', ['created_at'], unique=False)
    op.create_index(op.f('ix_badges_updated_at'), 'badges', ['updated_at'], unique=False)
    op.create_index(op.f('ix_courses_created_at'), 'courses', ['created_at'], unique=False)
    op.create_index(op.f('ix_courses_updated_at'), 'courses', ['updated_at'], unique=False)
    op.create_index(op.f('ix_exercises_created_at'), 'exercises', ['created_at'], unique=False)
    op.create_index(op.f('ix_exercises_updated_at'), 'exercises', ['updated_at'], unique=False)
    op.create_index(op.f('ix_lesson_sections_created_at'), 'lesson_sections', ['created_at'], unique=False)
    op.create_index(op.f('ix_lesson_sections_updated_at'), 'lesson_sections', ['updated_at'], unique=False)
    op.create_index(op.f('ix_lessons_created_at'), 'lessons', ['created_at'], unique=False)
    op.create_index(op.f('ix_lessons_updated_at'), 'lessons', ['updated_at'], unique=False)
    op.add_column('tests', sa.Column('course_id', sa.Integer(), nullable=True))
    op.alter_column('tests', 'topic_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_index(op.f('ix_tests_created_at'), 'tests', ['created_at'], unique=False)
    op.create_index(op.f('ix_tests_updated_at'), 'tests', ['updated_at'], unique=False)
    op.create_foreign_key(None, 'tests', 'courses', ['course_id'], ['id'])
    op.create_index(op.f('ix_topics_created_at'), 'topics', ['created_at'], unique=False)
    op.create_index(op.f('ix_topics_updated_at'), 'topics', ['updated_at'], unique=False)
    op.create_index(op.f('ix_user_badges_created_at'), 'user_badges', ['created_at'], unique=False)
    op.create_index(op.f('ix_user_badges_updated_at'), 'user_badges', ['updated_at'], unique=False)
    op.create_index(op.f('ix_user_courses_created_at'), 'user_courses', ['created_at'], unique=False)
    op.create_index(op.f('ix_user_courses_updated_at'), 'user_courses', ['updated_at'], unique=False)
    op.create_index(op.f('ix_user_lessons_created_at'), 'user_lessons', ['created_at'], unique=False)
    op.create_index(op.f('ix_user_lessons_updated_at'), 'user_lessons', ['updated_at'], unique=False)
    op.create_index(op.f('ix_user_states_created_at'), 'user_states', ['created_at'], unique=False)
    op.create_index(op.f('ix_user_states_updated_at'), 'user_states', ['updated_at'], unique=False)
    op.create_index(op.f('ix_user_topics_created_at'), 'user_topics', ['created_at'], unique=False)
    op.create_index(op.f('ix_user_topics_updated_at'), 'user_topics', ['updated_at'], unique=False)
    op.create_index(op.f('ix_users_created_at'), 'users', ['created_at'], unique=False)
    op.create_index(op.f('ix_users_updated_at'), 'users', ['updated_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_updated_at'), table_name='users')
    op.drop_index(op.f('ix_users_created_at'), table_name='users')
    op.drop_index(op.f('ix_user_topics_updated_at'), table_name='user_topics')
    op.drop_index(op.f('ix_user_topics_created_at'), table_name='user_topics')
    op.drop_index(op.f('ix_user_states_updated_at'), table_name='user_states')
    op.drop_index(op.f('ix_user_states_created_at'), table_name='user_states')
    op.drop_index(op.f('ix_user_lessons_updated_at'), table_name='user_lessons')
    op.drop_index(op.f('ix_user_lessons_created_at'), table_name='user_lessons')
    op.drop_index(op.f('ix_user_courses_updated_at'), table_name='user_courses')
    op.drop_index(op.f('ix_user_courses_created_at'), table_name='user_courses')
    op.drop_index(op.f('ix_user_badges_updated_at'), table_name='user_badges')
    op.drop_index(op.f('ix_user_badges_created_at'), table_name='user_badges')
    op.drop_index(op.f('ix_topics_updated_at'), table_name='topics')
    op.drop_index(op.f('ix_topics_created_at'), table_name='topics')
    op.drop_constraint(None, 'tests', type_='foreignkey')
    op.drop_index(op.f('ix_tests_updated_at'), table_name='tests')
    op.drop_index(op.f('ix_tests_created_at'), table_name='tests')
    op.alter_column('tests', 'topic_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('tests', 'course_id')
    op.drop_index(op.f('ix_lessons_updated_at'), table_name='lessons')
    op.drop_index(op.f('ix_lessons_created_at'), table_name='lessons')
    op.drop_index(op.f('ix_lesson_sections_updated_at'), table_name='lesson_sections')
    op.drop_index(op.f('ix_lesson_sections_created_at'), table_name='lesson_sections')
    op.drop_index(op.f('ix_exercises_updated_at'), table_name='exercises')
    op.drop_index(op.f('ix_exercises_created_at'), table_name='exercises')
    op.drop_index(op.f('ix_courses_updated_at'), table_name='courses')
    op.drop_index(op.f('ix_courses_created_at'), table_name='courses')
    op.drop_index(op.f('ix_badges_updated_at'), table_name='badges')
    op.drop_index(op.f('ix_badges_created_at'), table_name='badges')
    # ### end Alembic commands ###
