"""add_executable_column_to_exercises

Revision ID: 59b7be7ed199
Revises: dc1a793f14bd
Create Date: 2025-08-23 16:23:12.216659

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '59b7be7ed199'
down_revision: Union[str, None] = 'dc1a793f14bd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exercises', sa.Column('executable', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('exercises', 'executable')
    # ### end Alembic commands ###
