"""add column order to  topic table

Revision ID: 59c01fd93a40
Revises: 9f9338cb9efa
Create Date: 2025-07-06 18:39:26.190532

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '59c01fd93a40'
down_revision: Union[str, None] = '9f9338cb9efa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('document_processing_jobs', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('document_processing_jobs', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.create_index(op.f('ix_document_processing_jobs_created_at'), 'document_processing_jobs', ['created_at'], unique=False)
    op.create_index(op.f('ix_document_processing_jobs_updated_at'), 'document_processing_jobs', ['updated_at'], unique=False)
    op.add_column('topics', sa.Column('order', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('topics', 'order')
    op.drop_index(op.f('ix_document_processing_jobs_updated_at'), table_name='document_processing_jobs')
    op.drop_index(op.f('ix_document_processing_jobs_created_at'), table_name='document_processing_jobs')
    op.alter_column('document_processing_jobs', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('document_processing_jobs', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    # ### end Alembic commands ###
