"""remove duration, set column in exercise table

Revision ID: 5ae4593ef2c8
Revises: 7a81150504fb
Create Date: 2025-06-10 16:06:12.105482

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5ae4593ef2c8'
down_revision: Union[str, None] = '7a81150504fb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('exercises', 'duration')
    op.drop_column('exercises', 'sets')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exercises', sa.Column('sets', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('exercises', sa.Column('duration', sa.INTEGER(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
