"""support multiple exercises per lesson

Revision ID: 5cde50f49a21
Revises: 86f9aa50c44c
Create Date: 2025-06-30 17:03:52.339564

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5cde50f49a21'
down_revision: Union[str, None] = '86f9aa50c44c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('exercises_lesson_id_key', 'exercises', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('exercises_lesson_id_key', 'exercises', ['lesson_id'])
    # ### end Alembic commands ###
