"""add_course_draft_and_review_chat_tables

Revision ID: 64075549acc3
Revises: ec640e77e236
Create Date: 2025-08-03 06:53:41.966281

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '64075549acc3'
down_revision: Union[str, None] = 'ec640e77e236'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('user_courses_course_id_fkey'), 'user_courses', type_='foreignkey')
    op.create_foreign_key(None, 'user_courses', 'courses', ['course_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_courses', type_='foreignkey')
    op.create_foreign_key(op.f('user_courses_course_id_fkey'), 'user_courses', 'courses', ['course_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
