"""add_user_assessments_table

Revision ID: 727b15633bb0
Revises: 7314d79de250
Create Date: 2025-08-03 15:59:30.236048

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '727b15633bb0'
down_revision: Union[str, None] = '7314d79de250'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_assessments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('test_session_id', sa.String(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=True),
    sa.Column('strengths', sa.JSON(), nullable=True, comment='Điểm mạnh của người dùng'),
    sa.Column('weaknesses', sa.JSON(), nullable=True, comment='Điểm yếu của người dùng'),
    sa.Column('recommendations', sa.JSON(), nullable=True, comment='Khuyến nghị cải thiện'),
    sa.Column('skill_levels', sa.JSON(), nullable=True, comment='Mức độ kỹ năng theo từng chủ đề'),
    sa.Column('learning_path', sa.JSON(), nullable=True, comment='Lộ trình học tập được đề xuất'),
    sa.Column('overall_score', sa.Float(), nullable=True, comment='Điểm số tổng quan'),
    sa.Column('proficiency_level', sa.String(), nullable=True, comment='Mức độ thành thạo: beginner, intermediate, advanced'),
    sa.Column('analysis_summary', sa.Text(), nullable=True, comment='Tóm tắt phân tích'),
    sa.Column('raw_analysis', sa.JSON(), nullable=True, comment='Dữ liệu phân tích thô từ agent'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ),
    sa.ForeignKeyConstraint(['test_session_id'], ['test_sessions.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_assessments_course_id'), 'user_assessments', ['course_id'], unique=False)
    op.create_index(op.f('ix_user_assessments_created_at'), 'user_assessments', ['created_at'], unique=False)
    op.create_index(op.f('ix_user_assessments_id'), 'user_assessments', ['id'], unique=False)
    op.create_index(op.f('ix_user_assessments_test_session_id'), 'user_assessments', ['test_session_id'], unique=False)
    op.create_index(op.f('ix_user_assessments_user_id'), 'user_assessments', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_assessments_user_id'), table_name='user_assessments')
    op.drop_index(op.f('ix_user_assessments_test_session_id'), table_name='user_assessments')
    op.drop_index(op.f('ix_user_assessments_id'), table_name='user_assessments')
    op.drop_index(op.f('ix_user_assessments_created_at'), table_name='user_assessments')
    op.drop_index(op.f('ix_user_assessments_course_id'), table_name='user_assessments')
    op.drop_table('user_assessments')
    # ### end Alembic commands ###
