"""add_session_id_to_course_drafts

Revision ID: 7314d79de250
Revises: 11ef3ca88549
Create Date: 2025-08-03 10:50:16.230638

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7314d79de250'
down_revision: Union[str, None] = '11ef3ca88549'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('course_drafts', sa.Column('session_id', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('course_drafts', 'session_id')
    # ### end Alembic commands ###
