"""fix table lesson_generation_state

Revision ID: 7cc93ea5cd05
Revises: 59c01fd93a40
Create Date: 2025-07-07 17:07:46.995190

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7cc93ea5cd05'
down_revision: Union[str, None] = '59c01fd93a40'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('lesson_generation_states', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('lesson_generation_states', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               nullable=False)
    op.create_index(op.f('ix_lesson_generation_states_created_at'), 'lesson_generation_states', ['created_at'], unique=False)
    op.create_index(op.f('ix_lesson_generation_states_updated_at'), 'lesson_generation_states', ['updated_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_lesson_generation_states_updated_at'), table_name='lesson_generation_states')
    op.drop_index(op.f('ix_lesson_generation_states_created_at'), table_name='lesson_generation_states')
    op.alter_column('lesson_generation_states', 'updated_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.alter_column('lesson_generation_states', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    # ### end Alembic commands ###
