"""remove external_id lesson table

Revision ID: 7f29084dde83
Revises: 9e2dc2e5250a
Create Date: 2025-08-18 05:36:32.829236

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7f29084dde83'
down_revision: Union[str, None] = '9e2dc2e5250a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('courses', 'status',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.Enum('DRAFT', 'APPROVED', 'TOPIC_APPROVED', 'LESSON_APPROVED', 'EXERCISE_APPROVED', 'COMPOSITING', name='coursestatus', native_enum=False),
               existing_nullable=True)
    op.alter_column('exercise_test_cases', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('exercise_test_cases', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_exercise_test_cases_id'), table_name='exercise_test_cases')
    op.create_index(op.f('ix_exercise_test_cases_exercise_id'), 'exercise_test_cases', ['exercise_id'], unique=False)
    op.drop_column('exercises', 'name')
    op.drop_index(op.f('ix_lessons_external_id'), table_name='lessons')
    op.drop_column('lessons', 'external_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lessons', sa.Column('external_id', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.create_index(op.f('ix_lessons_external_id'), 'lessons', ['external_id'], unique=True)
    op.add_column('exercises', sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_exercise_test_cases_exercise_id'), table_name='exercise_test_cases')
    op.create_index(op.f('ix_exercise_test_cases_id'), 'exercise_test_cases', ['id'], unique=False)
    op.alter_column('exercise_test_cases', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('exercise_test_cases', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('courses', 'status',
               existing_type=sa.Enum('DRAFT', 'APPROVED', 'TOPIC_APPROVED', 'LESSON_APPROVED', 'EXERCISE_APPROVED', 'COMPOSITING', name='coursestatus', native_enum=False),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
    # ### end Alembic commands ###
