"""order unique for course

Revision ID: 8b2b7b3ae81a
Revises: eabf1d9c506b
Create Date: 2025-08-12 22:13:33.154532

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8b2b7b3ae81a'
down_revision: Union[str, None] = 'eabf1d9c506b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_topics_external_id'), table_name='topics')
    op.create_unique_constraint('uq_course_order', 'topics', ['course_id', 'order'])
    op.drop_column('topics', 'external_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('topics', sa.Column('external_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint('uq_course_order', 'topics', type_='unique')
    op.create_index(op.f('ix_topics_external_id'), 'topics', ['external_id'], unique=True)
    # ### end Alembic commands ###
