"""add_created_at_updated_at_to_test_sessions

Revision ID: 8b2e1f8bb9b1
Revises: fc360f416288
Create Date: 2025-06-27 13:24:09.138918

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8b2e1f8bb9b1'
down_revision: Union[str, None] = 'fc360f416288'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('test_sessions', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.add_column('test_sessions', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.alter_column('test_sessions', 'id',
               existing_type=sa.UUID(),
               type_=sa.String(),
               existing_nullable=False)
    op.create_index(op.f('ix_test_sessions_created_at'), 'test_sessions', ['created_at'], unique=False)
    op.create_index(op.f('ix_test_sessions_test_id'), 'test_sessions', ['test_id'], unique=False)
    op.create_index(op.f('ix_test_sessions_updated_at'), 'test_sessions', ['updated_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_test_sessions_updated_at'), table_name='test_sessions')
    op.drop_index(op.f('ix_test_sessions_test_id'), table_name='test_sessions')
    op.drop_index(op.f('ix_test_sessions_created_at'), table_name='test_sessions')
    op.alter_column('test_sessions', 'id',
               existing_type=sa.String(),
               type_=sa.UUID(),
               existing_nullable=False)
    op.drop_column('test_sessions', 'updated_at')
    op.drop_column('test_sessions', 'created_at')
    # ### end Alembic commands ###
