"""create discussions table

Revision ID: 95c7d27796fb
Revises: 47ad36ff4d24
Create Date: 2025-07-21 19:02:20.917543

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '95c7d27796fb'
down_revision: Union[str, None] = '47ad36ff4d24'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('discussions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_discussions_category'), 'discussions', ['category'], unique=False)
    op.create_index(op.f('ix_discussions_created_at'), 'discussions', ['created_at'], unique=False)
    op.create_index(op.f('ix_discussions_id'), 'discussions', ['id'], unique=False)
    op.create_index(op.f('ix_discussions_title'), 'discussions', ['title'], unique=False)
    op.create_index(op.f('ix_discussions_updated_at'), 'discussions', ['updated_at'], unique=False)
    op.create_index(op.f('ix_discussions_user_id'), 'discussions', ['user_id'], unique=False)
    op.create_table('replies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('discussion_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['discussion_id'], ['discussions.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_replies_created_at'), 'replies', ['created_at'], unique=False)
    op.create_index(op.f('ix_replies_discussion_id'), 'replies', ['discussion_id'], unique=False)
    op.create_index(op.f('ix_replies_id'), 'replies', ['id'], unique=False)
    op.create_index(op.f('ix_replies_updated_at'), 'replies', ['updated_at'], unique=False)
    op.create_index(op.f('ix_replies_user_id'), 'replies', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_replies_user_id'), table_name='replies')
    op.drop_index(op.f('ix_replies_updated_at'), table_name='replies')
    op.drop_index(op.f('ix_replies_id'), table_name='replies')
    op.drop_index(op.f('ix_replies_discussion_id'), table_name='replies')
    op.drop_index(op.f('ix_replies_created_at'), table_name='replies')
    op.drop_table('replies')
    op.drop_index(op.f('ix_discussions_user_id'), table_name='discussions')
    op.drop_index(op.f('ix_discussions_updated_at'), table_name='discussions')
    op.drop_index(op.f('ix_discussions_title'), table_name='discussions')
    op.drop_index(op.f('ix_discussions_id'), table_name='discussions')
    op.drop_index(op.f('ix_discussions_created_at'), table_name='discussions')
    op.drop_index(op.f('ix_discussions_category'), table_name='discussions')
    op.drop_table('discussions')
    # ### end Alembic commands ###
