"""add document processing jobs table with correct types

Revision ID: 9f9338cb9efa
Revises: f1b5e1065a63
Create Date: 2025-07-05 18:10:48.146475

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9f9338cb9efa'
down_revision: Union[str, None] = 'f1b5e1065a63'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('document_processing_jobs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('job_id', sa.String(), nullable=False),
    sa.Column('filename', sa.String(), nullable=False),
    sa.Column('document_url', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('result', sa.Text(), nullable=True),
    sa.Column('course_id', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('processed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_document_processing_jobs_id'), 'document_processing_jobs', ['id'], unique=False)
    op.create_index(op.f('ix_document_processing_jobs_job_id'), 'document_processing_jobs', ['job_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_document_processing_jobs_job_id'), table_name='document_processing_jobs')
    op.drop_index(op.f('ix_document_processing_jobs_id'), table_name='document_processing_jobs')
    op.drop_table('document_processing_jobs')
    # ### end Alembic commands ###
