"""update column exercise table

Revision ID: a70a2faa176f
Revises: 5ae4593ef2c8
Create Date: 2025-06-12 19:34:20.385060

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a70a2faa176f'
down_revision: Union[str, None] = '5ae4593ef2c8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exercises', sa.Column('suggest', sa.String(), nullable=True))
    op.alter_column('exercises', 'constraint',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('exercises', 'category')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exercises', sa.Column('category', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.alter_column('exercises', 'constraint',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('exercises', 'suggest')
    # ### end Alembic commands ###
