"""update index

Revision ID: a79cd52d8b9f
Revises: e73990e315cf
Create Date: 2025-07-13 05:07:19.820067

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a79cd52d8b9f'
down_revision: Union[str, None] = 'e73990e315cf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_lesson_sections_type', table_name='lesson_sections')
    op.create_index(op.f('ix_lesson_sections_lesson_id'), 'lesson_sections', ['lesson_id'], unique=False)
    op.drop_index('ix_lessons_description', table_name='lessons')
    op.drop_index('ix_lessons_title', table_name='lessons')
    op.create_index(op.f('ix_lessons_topic_id'), 'lessons', ['topic_id'], unique=False)
    op.drop_index('ix_topics_name', table_name='topics')
    op.create_index(op.f('ix_topics_course_id'), 'topics', ['course_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_topics_course_id'), table_name='topics')
    op.create_index('ix_topics_name', 'topics', ['name'], unique=False)
    op.drop_index(op.f('ix_lessons_topic_id'), table_name='lessons')
    op.create_index('ix_lessons_title', 'lessons', ['title'], unique=False)
    op.create_index('ix_lessons_description', 'lessons', ['description'], unique=False)
    op.drop_index(op.f('ix_lesson_sections_lesson_id'), table_name='lesson_sections')
    op.create_index('ix_lesson_sections_type', 'lesson_sections', ['type'], unique=False)
    # ### end Alembic commands ###
