"""update_user_model_relationships

Revision ID: b219bbe7291d
Revises: a1a7a09577ed
Create Date: 2025-04-17 22:09:39.874648

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b219bbe7291d'
down_revision: Union[str, None] = 'a1a7a09577ed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_states', sa.Column('completed_exercises', sa.Integer(), nullable=True))
    op.add_column('user_states', sa.Column('completed_courses', sa.Integer(), nullable=True))
    op.add_column('user_states', sa.Column('problems_solved', sa.Integer(), nullable=True))
    op.add_column('user_states', sa.Column('algorithms_progress', sa.Integer(), nullable=True))
    op.add_column('user_states', sa.Column('data_structures_progress', sa.Integer(), nullable=True))
    op.add_column('user_states', sa.Column('dynamic_programming_progress', sa.Integer(), nullable=True))
    op.drop_column('users', 'stats')
    op.drop_column('users', 'courses')
    op.drop_column('users', 'badges')
    op.drop_column('users', 'learning_progress')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('learning_progress', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('badges', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('courses', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('stats', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_column('user_states', 'dynamic_programming_progress')
    op.drop_column('user_states', 'data_structures_progress')
    op.drop_column('user_states', 'algorithms_progress')
    op.drop_column('user_states', 'problems_solved')
    op.drop_column('user_states', 'completed_courses')
    op.drop_column('user_states', 'completed_exercises')
    # ### end Alembic commands ###
