"""add user_course_progress table

Revision ID: b32e785910da
Revises: a79cd52d8b9f
Create Date: 2025-07-14 17:43:02.077454

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b32e785910da'
down_revision: Union[str, None] = 'a79cd52d8b9f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_course_progress',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_course_id', sa.Integer(), nullable=False),
    sa.Column('topic_id', sa.Integer(), nullable=False),
    sa.Column('lesson_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('NOT_STARTED', 'IN_PROGRESS', 'COMPLETED', name='progressstatus'), nullable=False),
    sa.Column('last_viewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_course_id'], ['user_courses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_course_progress_created_at'), 'user_course_progress', ['created_at'], unique=False)
    op.create_index(op.f('ix_user_course_progress_id'), 'user_course_progress', ['id'], unique=False)
    op.create_index(op.f('ix_user_course_progress_lesson_id'), 'user_course_progress', ['lesson_id'], unique=False)
    op.create_index(op.f('ix_user_course_progress_status'), 'user_course_progress', ['status'], unique=False)
    op.create_index(op.f('ix_user_course_progress_topic_id'), 'user_course_progress', ['topic_id'], unique=False)
    op.create_index(op.f('ix_user_course_progress_user_course_id'), 'user_course_progress', ['user_course_id'], unique=False)
    op.alter_column('exercises', 'lesson_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_index(op.f('ix_exercises_lesson_id'), 'exercises', ['lesson_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_exercises_lesson_id'), table_name='exercises')
    op.alter_column('exercises', 'lesson_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_index(op.f('ix_user_course_progress_user_course_id'), table_name='user_course_progress')
    op.drop_index(op.f('ix_user_course_progress_topic_id'), table_name='user_course_progress')
    op.drop_index(op.f('ix_user_course_progress_status'), table_name='user_course_progress')
    op.drop_index(op.f('ix_user_course_progress_lesson_id'), table_name='user_course_progress')
    op.drop_index(op.f('ix_user_course_progress_id'), table_name='user_course_progress')
    op.drop_index(op.f('ix_user_course_progress_created_at'), table_name='user_course_progress')
    op.drop_table('user_course_progress')
    # ### end Alembic commands ###
