"""add test_generation_status to course table

Revision ID: b72cba9a0dc1
Revises: 30c5b3b4b604
Create Date: 2025-06-26 19:39:26.303029

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "b72cba9a0dc1"
down_revision: Union[str, None] = "30c5b3b4b604"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "courses",
        sa.Column(
            "test_generation_status",
            sa.String(length=20),
            nullable=False,
            server_default="not_started",
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("courses", "test_generation_status")
    # ### end Alembic commands ###
