"""remove name and description from test table

Revision ID: bd81847fae83
Revises: 3f8b2e84b5eb
Create Date: 2025-06-27 02:21:35.251003

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bd81847fae83'
down_revision: Union[str, None] = '3f8b2e84b5eb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tests', 'name')
    op.drop_column('tests', 'description')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tests', sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('tests', sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
