"""exercise belong to lesson section

Revision ID: dc1a793f14bd
Revises: e99d803c85d8
Create Date: 2025-08-22 19:11:27.288156

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dc1a793f14bd'
down_revision: Union[str, None] = 'e99d803c85d8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_exercises_lesson_id'), table_name='exercises')
    op.drop_constraint(op.f('exercises_lesson_id_fkey'), 'exercises', type_='foreignkey')
    op.drop_column('exercises', 'lesson_id')
    op.add_column('lesson_sections', sa.Column('exercise_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'lesson_sections', 'exercises', ['exercise_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'lesson_sections', type_='foreignkey')
    op.drop_column('lesson_sections', 'exercise_id')
    op.add_column('exercises', sa.Column('lesson_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('exercises_lesson_id_fkey'), 'exercises', 'lessons', ['lesson_id'], ['id'])
    op.create_index(op.f('ix_exercises_lesson_id'), 'exercises', ['lesson_id'], unique=False)
    # ### end Alembic commands ###
