"""fix document processing jobs created_at default

Revision ID: e0dc8fd6b0f8
Revises: bdbb955bdf94
Create Date: 2025-07-11 09:41:35.901134

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "e0dc8fd6b0f8"
down_revision: Union[str, None] = "bdbb955bdf94"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Đặt server default cho created_at và updated_at
    op.alter_column(
        "document_processing_jobs",
        "created_at",
        existing_type=sa.DateTime(),
        nullable=False,
        server_default=sa.text("now()"),
    )
    op.alter_column(
        "document_processing_jobs",
        "updated_at",
        existing_type=sa.DateTime(),
        nullable=False,
        server_default=sa.text("now()"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Loại bỏ server default và cho phép nullable
    op.alter_column(
        "document_processing_jobs",
        "created_at",
        existing_type=sa.DateTime(),
        nullable=True,
    )
    op.alter_column(
        "document_processing_jobs",
        "updated_at",
        existing_type=sa.DateTime(),
        nullable=True,
    )
    # ### end Alembic commands ###
