"""replace current lesson id to current lesson order

Revision ID: e3fc31da60a9
Revises: 1d8c8dffe7ab
Create Date: 2025-07-11 10:44:38.213455

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e3fc31da60a9'
down_revision: Union[str, None] = '1d8c8dffe7ab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_topics', sa.Column('current_lesson_order', sa.Integer(), server_default='1', nullable=False))
    op.drop_constraint('user_topics_current_lesson_id_fkey', 'user_topics', type_='foreignkey')
    op.drop_column('user_topics', 'current_lesson_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_topics', sa.Column('current_lesson_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('user_topics_current_lesson_id_fkey', 'user_topics', 'lessons', ['current_lesson_id'], ['id'])
    op.drop_column('user_topics', 'current_lesson_order')
    # ### end Alembic commands ###
