"""remove user_topic table

Revision ID: e73990e315cf
Revises: e3fc31da60a9
Create Date: 2025-07-12 16:37:27.699377

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e73990e315cf'
down_revision: Union[str, None] = 'e3fc31da60a9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_user_topics_created_at', table_name='user_topics')
    op.drop_index('ix_user_topics_id', table_name='user_topics')
    op.drop_index('ix_user_topics_updated_at', table_name='user_topics')
    op.drop_table('user_topics')
    op.drop_column('courses', 'learning_path')
    op.add_column('user_courses', sa.Column('current_topic', sa.Integer(), nullable=False))
    op.add_column('user_courses', sa.Column('current_lesson', sa.Integer(), nullable=False))
    op.add_column('user_courses', sa.Column('current_section', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_courses', 'current_section')
    op.drop_column('user_courses', 'current_lesson')
    op.drop_column('user_courses', 'current_topic')
    op.add_column('courses', sa.Column('learning_path', sa.TEXT(), autoincrement=False, nullable=True))
    op.create_table('user_topics',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('topic_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('progress', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('completed_lessons', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('is_completed', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('current_lesson_order', sa.INTEGER(), server_default=sa.text('1'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.id'], name='user_topics_topic_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='user_topics_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='user_topics_pkey')
    )
    op.create_index('ix_user_topics_updated_at', 'user_topics', ['updated_at'], unique=False)
    op.create_index('ix_user_topics_id', 'user_topics', ['id'], unique=False)
    op.create_index('ix_user_topics_created_at', 'user_topics', ['created_at'], unique=False)
    # ### end Alembic commands ###
