"""update foreign key

Revision ID: e99d803c85d8
Revises: 2dd4aa3c9492
Create Date: 2025-08-22 11:15:25.138903

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e99d803c85d8'
down_revision: Union[str, None] = '2dd4aa3c9492'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'user_course_progress', 'lessons', ['lesson_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_course_progress', type_='foreignkey')
    # ### end Alembic commands ###
