"""add status column course table

Revision ID: eabf1d9c506b
Revises: 9245c18699fe
Create Date: 2025-08-11 21:49:09.261920

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eabf1d9c506b'
down_revision: Union[str, None] = '9245c18699fe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('courses', sa.Column('status', sa.String(length=255), nullable=True))
    op.drop_constraint(op.f('user_courses_course_id_fkey'), 'user_courses', type_='foreignkey')
    op.create_foreign_key(None, 'user_courses', 'courses', ['course_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_courses', type_='foreignkey')
    op.create_foreign_key(op.f('user_courses_course_id_fkey'), 'user_courses', 'courses', ['course_id'], ['id'], ondelete='CASCADE')
    op.drop_column('courses', 'status')
    # ### end Alembic commands ###
