"""add case column to exercises

Revision ID: ec640e77e236
Revises: aec009816870
Create Date: 2025-07-23 20:03:14.882095

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ec640e77e236'
down_revision: Union[str, None] = 'aec009816870'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exercises', sa.Column('case', sa.JSON(), nullable=True))
    op.drop_constraint(op.f('user_courses_course_id_fkey'), 'user_courses', type_='foreignkey')
    op.create_foreign_key(None, 'user_courses', 'courses', ['course_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_courses', type_='foreignkey')
    op.create_foreign_key(op.f('user_courses_course_id_fkey'), 'user_courses', 'courses', ['course_id'], ['id'], ondelete='CASCADE')
    op.drop_column('exercises', 'case')
    # ### end Alembic commands ###
