""" "add_lesson_generation_state_table"

Revision ID: f1b5e1065a63
Revises: 3f4d92aaa3b3
Create Date: 2025-07-05 04:53:23.448541

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "f1b5e1065a63"
down_revision: Union[str, None] = "3f4d92aaa3b3"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "lesson_generation_states",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("session_id", sa.String(), nullable=False),
        sa.Column("topic_id", sa.Integer(), nullable=False),
        sa.Column("lesson_id", sa.Integer(), nullable=True),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("request_data", sa.JSON(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["lesson_id"],
            ["lessons.id"],
        ),
        sa.ForeignKeyConstraint(
            ["topic_id"],
            ["topics.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_lesson_generation_states_id"),
        "lesson_generation_states",
        ["id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_lesson_generation_states_session_id"),
        "lesson_generation_states",
        ["session_id"],
        unique=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_lesson_generation_states_session_id"),
        table_name="lesson_generation_states",
    )
    op.drop_index(
        op.f("ix_lesson_generation_states_id"), table_name="lesson_generation_states"
    )
    op.drop_table("lesson_generation_states")
    # ### end Alembic commands ###
