name: Deploy

on:
  push:
    branches:
      - main
    paths:
      - server/**
      - '.github/workflows/deploy.yml'

jobs:
  build-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login docker
        uses: docker/login-action@v2
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: ./server
          push: true
          tags: ${{ vars.DOCKERHUB_USERNAME }}/server:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build-image
    steps:
      - name: Execute remote SSH commands using password
        uses: appleboy/ssh-action@v1
        env:
          DOCKERHUB_USERNAME: ${{vars.DOCKERHUB_USERNAME}}
        with:
          host: ${{ secrets.HOST_IP }}
          username: linuxserver.io
          key: ${{ secrets.HOST_PASSWORD }}
          script: ${{github.workspace}}/.github/scripts/deploy.sh